---
# tasks file for java_test

- name: check Java version 
  shell: java -version 2>&1 | grep 'version' | awk '{print $3}'      
  register: out

- debug: var=out.stdout

- name: check if java has port 8080 open
  shell: ss -tp state listening sport = :8080 | grep java
  become: yes


