---
# tasks file for nginx

- name: be sure Nginx is installed
  yum:  
    name: nginx
    state: present

- name: be sure nginx.conf not changed 
  template: 
      src: nginx.conf.j2d     
      dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: be sure Nginx service started
  service:  
    name: nginx
    enabled: yes
    state: started